### PR TITLE
single footprint from matrix of spatial data

### PR DESCRIPTION
**Pull request by jordansread**

### CODE REVIEW

**Comment by jordansread** [comment]
example data csv2: 
image

**Comment by jordansread** [comment]
example data csv1: 
image

**Comment by emhart** [comment]
@jread-usgs wow, that's fucking awesome man!  Sorry for the delay in adding the pr, I've been moving / on the road as soon as I came back from SB But this looks amazing.  I'll ping you when it's all integrated.  Thanks again for the great work.

**Comment by jordansread** [comment]
Thanks budddy

**Pull request merged**
